"""empty message

Revision ID: 2e93acf35f30
Revises: 9832b4b94108
Create Date: 2026-04-15 12:18:54.247216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e93acf35f30'
down_revision = '9832b4b94108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_hand_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('on_order_count', sa.Integer(), nullable=False))
        batch_op.drop_column('count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.INTEGER(), nullable=False))
        batch_op.drop_column('on_order_count')
        batch_op.drop_column('on_hand_count')

    # ### end Alembic commands ###
