"""empty message

Revision ID: 2fe8886b14b9
Revises: f1fe56f23494
Create Date: 2026-04-27 01:06:04.690559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe8886b14b9'
down_revision = 'f1fe56f23494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_table_product_id'))
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=False))
        batch_op.create_index(batch_op.f('ix_order_table_product_id'), ['product_id'], unique=1)

    # ### end Alembic commands ###
