"""empty message

Revision ID: 62ea26bf0188
Revises: 2fe8886b14b9
Create Date: 2026-04-27 09:44:26.851946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ea26bf0188'
down_revision = '2fe8886b14b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_order_table_product_id'), ['product_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_table_product_id'))
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
