"""empty message

Revision ID: a08255f1e005
Revises: 
Create Date: 2026-04-26 23:50:25.483567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08255f1e005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_table',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    with op.batch_alter_table('order_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_table_arrival_time'), ['arrival_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_table_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_table_timestamp'), ['timestamp'], unique=False)

    op.create_table('product_table',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=False),
    sa.Column('on_hand_count', sa.Integer(), nullable=False),
    sa.Column('on_order_count', sa.Integer(), nullable=False),
    sa.Column('stock_alert_minimum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    with op.batch_alter_table('product_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_table_product_id'), ['product_id'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('product_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_table_product_id'))

    op.drop_table('product_table')
    with op.batch_alter_table('order_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_table_timestamp'))
        batch_op.drop_index(batch_op.f('ix_order_table_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_table_arrival_time'))

    op.drop_table('order_table')
    # ### end Alembic commands ###
