"""empty message

Revision ID: c944bd4c05b6
Revises: 62ea26bf0188
Create Date: 2026-04-27 19:31:53.505389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c944bd4c05b6'
down_revision = '62ea26bf0188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_arrival_time'), ['arrival_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_product_id'), ['product_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('order_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_table_arrival_time'))
        batch_op.drop_index(batch_op.f('ix_order_table_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_table_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_table_timestamp'))

    op.drop_table('order_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_table',
    sa.Column('order_id', sa.CHAR(length=32), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('arrival_time', sa.DATETIME(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    with op.batch_alter_table('order_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_table_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_table_product_id'), ['product_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_order_table_order_id'), ['order_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_order_table_arrival_time'), ['arrival_time'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_timestamp'))
        batch_op.drop_index(batch_op.f('ix_order_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_arrival_time'))

    op.drop_table('order')
    # ### end Alembic commands ###
