"""empty message

Revision ID: f1fe56f23494
Revises: 26eee869b23d
Create Date: 2026-04-27 00:35:32.148570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fe56f23494'
down_revision = '26eee869b23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_table_product_id'), ['product_id'], unique=True)
        batch_op.drop_constraint(batch_op.f('fk_order_table_product_id_product_table'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_table', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_order_table_product_id_product_table'), 'product_table', ['product_id'], ['product_id'])
        batch_op.drop_index(batch_op.f('ix_order_table_product_id'))

    # ### end Alembic commands ###
